# Use official Node.js image as a base
FROM node:20-alpine

# Set environment variables
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Install global dependencies (if needed)
RUN npm install -g typescript

# Copy application files
COPY . .

# Build Next.js application
RUN npm run build

# Expose the port that the Next.js app will run on
EXPOSE 3000

# Set the environment to production
ENV NODE_ENV=production

# Command to start the Next.js application
CMD ["npm", "run", "start"]