# Use a compatible Node.js version for Strapi
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json package-lock.json ./

# Install global dependencies (if needed)
RUN npm install -g node-gyp

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port (default Strapi port is 1337)
EXPOSE 1338

# Start Strapi application
CMD ["npm", "run", "develop"]